# 学习和研究数学的一些体会 {.unnumbered}

人贵有自知之明。我知道，我对科学研究的了解不全面。也知道，搞科学极重要的是独立思考，各人应依照各人自己的特点找出最适合的道路。听了别人的学习、研究方法，就以为我也会学习研究了，这个就无异于吃颗金丹就会成仙，而无需经过勤修苦练了。  

今天把我五十年来的经验教训，所见所闻、所体会的给你们介绍，目的在于尽可能把我的经验作为你们的借鉴，具体问题具体分析，具体的个人应当想出最适于自己的有效方法来。  

**我第一点准备和同志们谈的问题是速度、是效率**。速度是实现社会主义现代化的保证。例如说象我这样又老又拐的人，我在前头走你们赶我不费劲，一赶就赶上，而我要赶你们，除非你们躺下来睡大觉，否则我无论如何是赶不上的。现在世界上科学发展很快，我们如果没有超过美国的速度和效率就不可能赶上美国。我们没有超过日本的速度和效率，我们就不可能赶上日本。如果我们的速度仅仅和美、日等国一样，那么也只能是等时差的赶，超就是一句空话。所以说，我们应当首先在速度和效率上超过他们。  
但要我们的速度和效率超过他们有没有可能呢？这似乎是一个大问题，其实不然，我在美国呆过，在英国呆过，也在苏联呆过。我看到他们的速度不是神话般的快不可及。我们是赶得上超得过的！我们许多美籍华人，如果他们的速度不能超过一般的美国人的话，也就不会成为现代著名的科学家了。所以事实证明，只要我们努力下功夫，赶超是完全可以的。就以我自己来说，我是三六年到英国的，在那里呆了两年，回国后在昆明乡下住了两年，四零年就完成了堆垒素数论的工作。后来五零年回国后，在五八年之前，我们的数论、代数、多复变函数论等等都达到了世界上的良好的水平。所以经验告诉我们纯数学的一门学科，有四五年就能在世界上见头角了。你们现在时代更好了，党中央一举粉碎了“四人帮”，带来了科学的春天。在这样的条件下边，我敢断言，只要肯下功夫，努力钻研，只要不浪费一分一秒的时间，我们是能够赶上世界先进水平的。特别是我们数学，前有熊庆来、陈建功、苏步青等老前辈的榜样，现在又有许多后起之秀，更多的后起之秀也一定会接踵而来。  
**二、消化**  抢速度不是越级乱跳，不是一本书没有消化好就又看一本，一个专业没有爬到高处就又另爬一个山峰。我们学习必须先从踏踏实实地读书讲起，古时候总说这个人“博闻强记”“学富五车”。实际上古人的这许多话到现在已是不足为训了。五车的书，从前是那种大字的书，我想一个指甲大小的集成电路就可以装它五本十本，学书五车，也不过十几块几十块集成电路而已。现在也有相似的看法，说某人念了多少多少书，某人对世界上的文献记的多熟多熟，当然这不是不必要的，而这只能说走了开始的第一步，如果不经过消化，实际抵不上一个图书馆，抵不上一个电子计算机的记忆系统。人之所以可贵就在于会创造，在于善于吸收过去的文献的精华，能够经过消化创造前人所没有的东西。不然人云亦云世界就没有发展了，懒汉思想是科学的敌人，当然也是社会发展的敌人。  

什么是消化？检验消化的最好的方法就是“用”。会用不会用，不是说空话，而是在实际中考验。碰到这个问题束手无策，碰到那个问题又是一筹莫展，即使他能写几篇模仿性的文章，写几本抄抄译译的稿著，这同社会的发展又有什么关系呢？当然我不排斥初学的人写几篇模仿性的文章，但绝不能局限于此，须发皆白还是如此。 

消化，只有消化后，我们才会灵活运用。如果社会主义建设需要我们，我们就会为社会主义建设服务，解决问题，贡献力量。客观的问题上面不会贴上标签的，告诉你这需要用数论，那个是要用泛函，而社会主义建设所提出来的问题是各种各样无穷无尽的，想用一个方法套上所有的实际问题，那就是形而上学的做法。只有经过独立思考和认真消化的学者，才能因时因地根据不同的问题，运用不同的方法真正解决问题。

当然，刚才说消化不消化只有在实际中进行检验。但是同学们不一定就有那么多的实践机会，在校学习的时候有没有检查我们消化了没有的方法呢？我以前讲过，学习有一个由薄到厚，再由厚到薄的过程。你初学一本书，加上许多注解，又看了许多参考书，于是书就由薄变厚了。自己以为这就是懂了，那是自欺欺人，实际上这还不能算懂。而真正懂，还有一个由厚到薄的过程。也就是全书经过分析，扬弃枝节，抓住重点，甚至于来龙去脉都一目了然了，在没有这条定理前，人家是怎样想出来的，这样才能说是开始懂了，这也是一个检验自己是否消化了的方法。当然，这个方法不如前面那种更踏实。总的一句话，检验我们消化没有，弄通没有的最后标准是实践，是能否灵活运用解决问题。也许有人会说这样念书太慢了。我的体会不是慢了，而是快了。因为我们消化了我们以前念过的书，再看另一本书时，我们脑子里的记忆系统就会排除那些过去弄懂了的东西。而只注意新书中自己还没有碰到过的新东西。所以说，这样脚踏实地的上去，不是慢了而是快了。不然的话囫囵吞枣的学了一阵，忘掉一阵，再学再忘，白费时光事小，使自己“于国于家无望”事大。更可怕的是好高骛远。例如中学数学没学懂，他已读到大学三、四年级的课程，遇到困难，但又不屑于回去复习，再去弄通中学的东西，这样前进，就愈进愈糊涂，陷入泥坑，难于自拔。有时候阅读同一水平的书，如果我们以往的书弄懂了消化了，那么在同一水平书里找找以往书上没有的东西就可以过去了。找不到很快送上书架，找到一点两点就只要把这一两点弄懂就得了，这样读书就快了，不是慢了。

读书得法了，然后看文献，实际上看文献和看书没有什么不同，也是要消化。不过书上是比较成熟的东西，去粗取精，则精多粗少。而文献是刚出来的，往往精少而粗多。当然不排除有些文章，一出来就变成经典著作的情况。但这毕竟是少数的少数。不过多数文章通过不多时间就被人们遗忘了。有了吸取文献的基础，就可以搞研究工作。

这里我还要强调一下独立思考。独立思考是搞科学研究的根本，在历史上，重大的发明没有一个是不通过独立思考就能搞出来你的。当然这并不等于说不接受前人的成就而“独立”“思考”。例如有许多人，搞哥德巴赫猜想，对前人的工作一无所知，这样搞，成功的可能性是很小的。独立思考也并不是说不要攻书，不要看文献，不要听老师的讲述了。书本、文献、老师都是要的，但如果拘泥于这些，就会失去创造力，使学生变成教师的一部分，这样就会愈缩愈小，数学上出了收敛的现象。只有独立思考才能够跳出这个框框，创造出新的方法，创造出新的领域，推动科学的进步。独立思考不是说一个人独自在那里冥思苦想，不和他人交流。独立思考也要借助别人的结果，也要依靠群众和集体的智慧。独立思考也可以补救我们现在导师不够，导师经验较差，导师太忙顾不过来，但这都需独立思考来补救。甚至于象我们过去在昆明被封锁的时候，外国杂志没处来，我们还是独立思考，想出新的东西来，而想出来的东西和外国人并重复。即使有，也别怕。例如说，我青年时在家里发表过几篇文章，而退稿的很多，原因是别人说你的这篇文章那本书里已有此定理了，那篇文章在某书里也已有证明了等等。面对这种情况是继续干呢？还是就泄气呢？觉得上不起学，老是白费时间搞前人所搞过的东西。当时，我并没有这样想，在收到退稿时反而高兴，这是我明白，原来某大科学家搞过的东西，我在小店里也能搞出来。因此我还是加倍继续坚持搞下去了。我这里并不是说过去的文献不要看，而是说即使重复了人家的工作也不要泄气，要对比一下自己搞出来的同已有的有什么区别，是不是他们的比我们的好，这样就学习人家长处，就有进步，如果我们还有长处就增加了信心。

我们有了独立思考，没有导师或文献不全，就都不会成为我们的阻力。相反，有导师我们也还要考虑考虑讲的话对不对，文献是否完整了……。总之，科学事业是善于独立思考的人所创造出来的，而不是象我前面所说的等于几块集成电路的那种人创造出来的，因为这种人没有创造性。毛主席指出：研究问题，要由此及彼，由表及里，去粗取精，去伪存真。做到这四点，就非靠独立思考不可，不独立思考就只得其表，取其粗，只能够伪善杂存，无法明辨是非。

















