# 数学的用场与发展 {.unnumbered}

数(读作shu 四声)起源于数(读作shu三声)，如一、二、三、四、五……，一个、两个、三个……。量起源于量。先取一个单位标准，然后一个单位一个单位地量。天下虽有各种不同的量(各种不同的量的单位如尺、斤、 斗、秒、伏特、欧姆和卡路里等等)，但都必须通过数才能确切地把实际的情况表达出来。所以“数”是各种各样不同量的 共性，必须通过它才能比较量的多寡，才能说明量的变化。  

“量”是贯穿到一切科学领域之内的，因此数学的用处也就渗透到一切科学领域之中。凡是要研究量、量的关系、量的变化、量的关系变化、量的变化的关系的时候，就少不了数学。不仅如此，量的变化还有变化，而这种变化一般也是用量来刻划的。例如，速度是用来描写物体的变化的动态的。而加速度则是用来刻划速度的变化。量与量之间有各种各样的关系，各种各样不同的关系之间还可能有关系。为数众多的关系还有主从之分—也就是说，可以从一些关系推导出另一些关系来。所以数学还研究变化的变化，关系的关系，共性的共性，循环往复，逐步提高，以至无穷。  

数学是一切科学得力的助手和工具。它有时由于其他科学的促进而发展，有时也先走一步，领先发展，然后再获得应用。任何一门科学缺少了数学这一项工具便不能确切地刻划出客观事物变化的状态，更不能从已知数据推出未知的数据来，因面就减少了科学预见的可能性，或者减弱了科学预见的精确度。  

恩格斯说：“纯数学的对象是现实世界的空间形式和数量关系。”数学是从物理模型抽象出来的、它包括数与形两方面的内容。以上只提要地讲了数最关系，现在我们结合宇宙之大来说明空间形式。

## 宇宙之大 {.unnumbered}

宇宙之大，宇宙的形态，也只有通过数学才能说得明白。天圆地方之说，就是古代人民用几何形态来描绘客观宇宙的尝试。这种“苍天如圆盖，陆地如棋局”的宇宙形态的模型，后来被航海家用事实给以否定了。但是，我国从理论上对这一模型提出的怀疑要早得多，并且也同样的有力。论点是：“混沈初开，乾坤始奠，气之轻清上浮者为天，气之重浊者下凝者为地。”但不知轻清之外，又有何物？也就是圆盖之外，又有何物？三十三天之上又是何处？要想解决这样的问题，就必须借助于数学的空间形式的研究。

四维空间听来好象有些神秘，其实早已有之，即以“宇宙”二字来说，“四方上下曰宇，往古来今曰宙，以喻天地”(《准南子·原道》）。就是宇是东西、南北、上下三维扩展的空间，而宙是一维的时间。牛顿时代对宇宙的认识也就是如此。宇宙是一个无边无际的三维空间，而一切的日月星辰都安排在这框架中运动。找出这些星体的运动规律是牛顿的一大发明。也是物理模型促进数学方法，而数学方法则是用来说明物理现象的一个好典范。由于物体的运动：不是等加速度，要描绘不是等加速度，就不得不考虑速度时时在变化的情况。于是既创造了新工具——微积分，又发现了万有引力定律。有了这些，宇宙间一切星辰的运动初步统一地被解释了。行星凭什么以椭圆轨道绕日而行的，何时以怎样的速度，达到何处等，都可以算出来了。

有人说西方文明之飞速发展是由于欧几里得几何的推理方法和进行系统实验的方法。牛顿的工作也是逻辑推理的一个典型。他用简单的几条定律推出整个的力学系统.大至解释天体的运行，小到造房、修桥、杠杆、称物都行。但是人们在认识自然界而建立的理论总是不会一劳永逸完美无缺的，牛顿力学不能解释的问题还是有的。用它解释了行星绕日公转，但行星自转又如何解释呢？地球自转一天24小时有昼有夜。还有一个有名的问题：水星进动每百年42".这是牛顿力学无法解释的。

爱因斯坦不再把“宇”、“宙”分开来看，也就是时间也在进行着。每一瞬间三维空间中的物质在占有它一定的位置。他根据麦克斯韦-洛伦兹的光速不变假定，并继承了牛顿的相对性原理而提出了狭义相对论。狭义相对论中的洛伦兹变换把时空联系在一起，当然并不是消灭了时空特点。如向东走三里，再向西走三里，就回到原处，但时间则不然，共用了走六里的时间。时间是一去不复返地流逝着。值得指出的是有人推算出狭义相对论不但不能解释水星进动问题，而且算出的结果是“退动”。这是误解。我们能算出进动28”，即客观数的三分之二。另外，有了深刻的分析，反而能够浅出，连微积分都不要用，并且在较少的假定下，就可以推出爱因斯坦狭义相对论的全部结果。

爱因斯坦进一步把时、空、物质联系在一起，提出了广义相对论。用它可以算出水星进动是43”，这是支持广义相对论的一个有力证据。由于证据还不多，因此对广义相对论还有不少看法，但它的建立有赖于数学上的先行一步。如先有了黎曼几何。另一方面它也给数学提出了好些到现在还没有解决的问题。对宇宙的认识还将有多么大的进展，我不知道，但可以说，每一步都是离不开数学这个工具的。

## 粒子之微 {.unnumbered}

佛经上有所谓“金栗世界”，也就是一粒粟米也可以看作一个世界。这当然是佛家的幻想。但是我们今天所研究的原子却远远地小于一粒栗米，而其中的复杂性却不亚于一个太阳系。

即使研究这样小的原子核的结构也还是少不了数学。描述原子核内各种基本粒子的运动更是少不了数学。能不能用处理普遍世界的方法来处理核子内部的问题呢？情况不同了！在这里，牛顿的力学，爱因斯坦的相对论都遇到了困难。在目前人们应用了另一套数学工具。如算子论，群表示论，广义函数论，固体子等。这些工具都是近代的产物。即使如此，也还是不能完整地说明它。

在物质结构上不管分子论、原子论也好，或近代的核子结构、基本粒子的互变也好，物理科学上虽然经过了多次的概念革新，但自始至终都和数学分不开。不但今天，就是将来，也有一点是可以肯定的，就是一定还要用数学。

是否有一个统一的处理方法，把宏观世界和微观世界统一在一个理论之中，把四种作用力统一在一个理论之中，这是物理学家当前的重大问题之一。不管将来他们怎样解决这个问题，但是在处理这些问题的数学方法必须统一。必须有一套既可以解释宏观世界又可以解释微观世界的数学工具。数学一定和物理学刚开始的时候一样，是物理科学的助手和工具。在这样的大间题的解决过程中，也可能如牛顿同时发展天体力学和发明微积分那样促进数学的新分支的创造和形成。

## 火箭之速 {.unnumbered}

在今天用“一日千里”来形容慢则可，用来形容快则不可了！人类可创造的物体的速度远远地超过了“一日千里”。飞机虽快到日行万里不夜，但和宇宙速度比较，也显得缓慢得很。

不妨回忆一下，在星际航行的开端—由诗一般的幻想进入科学现实的第一步，就是和数学分不开的。早在牛顿时代就算出了每秒钟近八公里的第一字宙速度，这给科学技术工作者指出了奋斗目标。如果能够达到这一速度，就可以发射地球卫星。1970年我国发射了第一颗人造卫星，东方红的歌声传遍了全世界。数学工作者自始至终都参与这一工作（当然，其中不少工作者不是以数学工作者见称，而是运用数学工具者）。作为人造行星环绕太阳运行所必须具有的速度是11.2公里/秒，称为第二宇宙速度；脱离太阳系飞向恒屋际空间所必须具有的速度是16.7公里/秒，称为第三宇宙速度。这样的目标，也将会逐步去实现。

顺便提一下，如果我们宇宙航船到了一个星球上，那儿也有如我们人类一样高级的生物存在。我们用什么东西作为我们之间的媒介。带幅画去吧，那边风景殊，不了解。带一段录音去吧，也不能沟通。我看最好带两个图形去。一个“数”，一个“数形关系”（勾股定理）（图1和图2）。

为了使那里较高级的生物知道我们会几何证明，还可送去下面的图形。即“青出朱入图”（图3）。这些都是我国古代数学史上的成就。

## 化工之巧 {.unnumbered}

化学工业制造出的千千万万种新产品，使人类的物质生活更加丰富多彩，真是“巧夺天工”，“巧夺造化之工”。在制造过程中，它的化合和分解方式是用化学方程来描述的，但它是在变化的，因此，伟大革命导师恩格斯明确指出：“表示物体的分子组合的一切化学方程式，就形式来说是微分方程式。但是这些方程式实际上已经由于其中表示的原子量而积分起来了。化学所计算的正是量的相互关系为已知的微分。”

为了形象化地说明，例如，某种物质中含有硫，用苯提取硫。苯吸取硫有一定的饱含量，在这个过程中，苯含硫越多越难再吸取硫，剩下的硫越少越难被苯吸取。这个过程时刻都在变化的，吸收过程速度在不断减慢着。实验本身便是这个过程的积分过程，它的数学表达形式就是微分方程式及其求解。简单易作的过程我们可以用实验去解决。但对于复杂、难作的过程，则常常需要用数学手段来加以解决。特别是选取最优过程的工艺，数学手段更成为必不可少的手段。特别是量子化学的发展，使得化学研究提高到量子力学的阶段，数学手段—微分方程及矩阵图论更是必需的数学工具。

应用了数学方法还可使化学理论问题得到极大的简化。例如，对于共轮分子的能级计算，在共轮分子增大时十分困难。应用了分子轨道的图形理论，由图象形来简化计算，取得了十分直观和易行的效果，便是一例。其主要根据是如果一个行列式中的元素为0的多，那就可以用图论来简化计算。

## 地球之变 {.unnumbered}

我们所生活的地球处于多变的状态之中，从高层的大气，到中层的海洋，下到地壳，深入地心都在剧烈地运动着，而这些运动规律的研究也都用到数学。

大气环流，风云雨雪，天天需要研究和预报，使得农民可以安排田间农活，空中交通运输可以安排航程。限风等灾害性天气的预报，使得海军，渔民和沿海地区能够及早预防，减少损害。而所有这些预报都离不了数学。

“风乍起，吹皱一池春水”。风和水的关系自古便有记述，“无风不起浪”。但是风和浪的具体关系的研究，则是近代才逐步弄清的，而在风与浪的关系中用到了数学的工具，例如偏微分方程的间断解的问题。

大地每年有上百万次的地震，小的人感觉不到，大的如果发生在人烟稀少的地区，也不成大灾。但是每年也有几次在人口众多的地区的大震，形成大灾。对地壳运动的研究，对地震的预报，以及将来进一步对地震的控制都离不开数学工具。

## 生物之谜 {.unnumbered}

生物学中有许许多多的数学问题。蜜蜂的蜂房为什么要象如下的形式（图4),一面看是正六角形，另一面也是如此。但蜂房并不是六棱柱，而它的底部是由三个菱形所拼成的。图5是蜂房的立体图。这个图比较清楚，更具体些，拿一支六棱柱的铅笔未削之前，铅笔一端形状是ABCDEF正六角形（图6)。通过AC,一刀切下一角，把三角形ABO搬置AOO处。过AE,CE也如此同样切三刀，所堆成的形状就是图7,而蜂巢就是两排这样的蜂房底部和底部相接而成。

关于这个问题有一段趣史：巴黎科学院院士数学家克尼格，从理论上计算为使消耗材料最少菱形的两个角度应该是109°26’和70°34’。与实际蜜蜂所做出的仅相差2分。后来苏格兰数学家马克劳林重新计算，发现错了的不是小小的蜜蜂，而是巴黎科学院的院士因克尼格用的对数表上刚好错了一个字。这十八世纪的难题，1964年我用它来考过高中生，不少高中生提出了各种各样的证明。

这一问题，我写得篇幅略长些，目的在于引出生物之谜中的数学，另一方面也希望生物学家给我们多提些形态的问题。蜂房与结晶学联系起来，这是“透视石”的晶体。再回到化工之巧，有多少种晶体可以无穷无尽、无空无隙地填满空间，这又要用到数学。数学上已证明，只有230种。

还有如膜岛素的研究中，由于复杂的立体模型也用了复杂的数学计算。生物遗传学中的密码问题是研究遗传与变异这一根本问题的，它的最终解决必然要考虑到数学问题。生物的反应用数学加以描述成为工程控制论中“反馈”的泉源。神经作用的数学研究为控制论和信息论提供了现实的原型。

## 日用之繁 {.unnumbered}

日用之繁，的确繁，从何谈起真为难！但也有容易处。日用之繁与亿万人民都有关，只要到群众中去，急工农之所急，急生产和国防之所急，不但可以知道哪些该搞，而且知道轻重缓急。群众是真正的英雄，遇事和群众商量，不但政治上有提高，业务上也可以学到书本上所读不到的东西。象我这样自学专攻数学的，也在各行各业师傅的教育下，学到了不少学科的知识，这是一个大学一个专业中所学不到的东西。

我在日用之繁中搞些工作始于大跃进的1958年，但真正开始是1964年接受毛主席的亲笔指示后。并且使我永远不会忘记的是在我刚迈出一步写了《统筹方法平话》下到基层试点时，毛主席又为我指出：“不为个人而为人民服务，十分欢迎”的奋斗目标。后来在敬爱的周总理关怀下又摘了《优选法》。由于各省、市、自治区的领导的关怀，我曾有机会到过二十个省市、下过数以千计的工矿农村，拜得百万工农老师，形成了以具有实践经验的工人为主体的三结合的小分队。通
过群众性的科学实验活动证明，数学确实大有用场，数学方法用于革新挖潜，能为国家创造巨大的财富。回顾已往，真有“抱着金饭碗讨饭吃”之感。

由于我们社会主义制度的优越性，在这一方面可能有我们自己的特点，不妨结合我下去后的体会多谈一些。

统筹方法不仅可用于一台机床的维修、一所房屋的修建、一组设备的安装、一项水利工程的施工，更可用于整个企业管理和大型重点工程的施工会战。大庆新油田开发，万人千台机的统筹，黑龙江省林业战线采、运、用、育的统筹，山西省大同市口泉车站运煤的统筹，太原铁路局太钢和几个工矿的联合统筹，还有一些省市公社和大队的农业生产统筹等等，都取得了良好效果。看来统筹方法宜小更宜大。大范围的过细统筹效果越好，油水越大。

为了贯彻统筹兼顾、合理安排的思想，统筹方法仅提供了一个辅助工具。初步看来潜力不小，特别是把方法交给广大群众，结合具体实际，大家动手搞起来，由小到大、由简到繁，在普及的基础上进一步提高，收效甚大。初步设想可以概括成十二个字：大统筹，理数据，建系统，策发展，使之发展成一门学科—统筹学，以适应我国的具体情况，体现我们社会主义社会的特点。统筹的范围越大，得到和用到的数据也越多。我们不仅仅是统计这些数据，而且还要从这些数据中取出尽可能多的信息来作为指导。因此数据处理提到了日程上来。数据纷繁就要依靠电子计算机。新系统的建立和旧系统的改建和扩充，都必须在最优状态下运行。更进一步就是策发展，根据今年的情况明年如何发展才更积极又可靠，使国民经济的发展达到最大可能的高速度。

优选法是采用尽可能少的试验次数，找到最好方案的方法。优选学作为这类方法的数学理论基础，已有初步地系统研究。实践中，优选法的基本方法，已在大范围内得到推广。目前，我国化工、电子、冶金、机械、轻工、纺织、交通、建材等等方面都有较广泛地应用。在各级党委的领导下，大摘推广应用优选法的群众运动，各行各业搞，道道工序搞，短期内就可以应用优选法开展数以万计项目的试验。使原有的工艺水平普遍提高一步。在不添人、不增设备、不加或少加投资的情况下，就可收到优质、高产、低耗的效果。例如，小型化铁炉，优选炉形尺寸和操作条件，可使焦铁比一般可达1:18。机械加工优选刀具的几何参数和切削用量，工效可成倍提高。烧油锅炉，优选喷枪参数，可以达到节油不冒黑烟。小化肥工厂搞优选，既节煤又增产。在大型化工设备上搞优选，提高收率潜力更大。解放牌汽车优选了化油器的合理尺寸，一辆汽车一年可节油一吨左右，全国现有民用汽车都来推广，一年就可节油六十余万吨。粮米加工优选加工工艺，一般可提高出米率百分之一、二、三，提高出粉率百分之一。若按全国人数的口粮加工总数计算，一年就等于增产几亿斤粮食。

最好的生产工艺是客观存在的，优选法不过是提供了认识它的、尽量少做试验、快速达到目的的一种数学方法。

物资的合理调配，农作物的合理分布，水库的合理排灌，电网的合理安排。工业的合理布局，都要用到数学才能完满解决，求得合理的方案。总之一句话，在具有各种互相制约、互相影响的因素的统一体中，寻求一个最合理《依某一目的，如最经济，最省人力）的解答便是一个数学问题，这就是“多、快、好、省”原则的具体体现。所用到的数学方法很多，其中确属适用者我们也准备了一些，但由于林彪、“四人帮”一伙的干扰破坏，没有力量进行深入的工作。今天科技工作要大干快上。用于“当务之急”的数学研究和应用必将出现一个崭新的局面。

## 数学之发展 {.unnumbered}

宇宙之大，粒子之微，火箭之速，化工之巧，地球之变，生物之谜，日用之繁，无处不用数学。其它如爱因斯坦用数学工具所获得的公式指出了寻找新能源的方向，并且还预示出原子核破裂发生的能量的大小。在天文学上，也是先从计算上指出海王星的存在，而后发现了海王星。又如高速飞行中，由次音速到超音速时出现了突变，而数学出现了混合型偏微分方程的研究。还有无线电电子学与计算技术同信息论的关系，自动化与控制技术同常微分方程的关系，神经系统同空制论的关系，形态发生学与结构稳定性的关系等等，不胜枚举。

数学是一门富有概括性的学问。抽象是它的特色。同是一个方程，弹性力学上是描写振动的，流体力学上却描写了流体动态，声学家不妨称它是声学方程，电学家也不妨称它为电报方程，而数学家所研究的对象正是这些现象的共性的一面——双曲型偏微分方程。这个偏微分方程的解答的性质就是这些不同对象的共同性质，数值的解答也将是它所联系各学科中所要求的数据。

不但如此，这样的共性，一方面可以促成不同分支产生统一理论的可能性，另一方面也可以促成不同现象间的相互
模拟性。例如：声学家可以用相似的电路来研究声学现象，这大大地简化了声学实验的繁重性。这种模拟性的最普遍的
应用便是模拟电子计算机的产生。根据神经细胞有兴奋与抑制两态，电学中有带电与不带电两态，数学中二进位数的0
与1、逻辑中的“是”与“否”，因而有用电子数字计算机来模拟神经系统的尝试，及模拟逻辑思维的初步成果。

我们作如上的说明，并不意味着数学家可以自我陶醉于共性的研究之中。一方面我们得承认，要求数学家深入到研
究对象所联系的一切方面是十分困难的，但是这并不排斥数学家应当深入到他所联系到的为数众多的科学之一或其中的
一部分。这样的深入是完全必要的。这样做既对国民经济建设可以做出应有的贡献，而且就是对数学本身的发展也有莫
大好处。

客观事物的出现一般讲来有两大类现象。一类是必然的现象——或称因果律。一类是大数现象——或称机遇律。表
示必然现象的数学工具一般是方程式，它可以从已知数据推出未知数据来，从已知现象的性质推出未知现象的性质来。
通常出现的有代数方程，微分方程，积分方程，差分方程等等（特别是微分方程）。处理大数现象的数学工具是概率论与
数理统计。通过这样的分析便可以看出大势所趋，各种情况出现的比例规律。

数学的其它分支当然也可以直接与实际问题相联系。例如：数理逻辑与计算机自动化的设计，复变函数论与流体力
学，泛函分析与群表示论与量子力学，黎曼几何与相对论等等。在计算机设计中也用到数论。一般说来，数学本身是一个
互相联系的有机整体、而上面所提到的两方面是与其它科学接触最多最广泛的。

计算数学是一门与数学的开始而俱生的学问，不过今天由于快速大型计算机的出现特别显示出它的重要性。因为对
象日繁，牵涉日广（一个问题的计算工作量大到了前所未有的程度）。解一个一百个未知数的联立方程是今天科学中常见
的（如水坝应力，大地测量，设计吊桥，大型建筑等等）,仅靠笔算就很困难。算一个天气方程，希望从今天的天气数据
推出明天的天气数据，单凭笔算要花成年累月的时间。这样算法与明天的天气何干？一个讽刺而已！电子计算机的发明
就满足了这种要求。高速度大存储量的计算机的发展改变了科学研究的面貌，但是近代的电子计算机的出现丝毫没有减
弱数学的重要性，相反地更发挥数学的威力，对数学的要求提得更高。繁重的计算劳动减轻了或解除了，而创造性的劳
动更多了。计算数学是一个桥梁，它把数学的创造同实际结合起来。同时它本身也是一个创造性的学科。例如推动了一
个新学科计算物理学的发展。

除掉上面所特别强调的分支以外，并不是说数学的其余部分就不重要了。只有这些重点部门与其它部分环环扣紧，
把纯数学和应用数学都分工合作地发展起来，才能既符合我国当前的需要，又符合长远需要。

从历史上数学的发展的情况来看。社会愈进步，应用数学的范围也就会愈大，所应用的数学也就愈精密，应用数学
的人也就愈多。在日出而作，日入而息的古代社会里，会数数就可以满足客观的需要了。后来由于要定四时，测田亩，
于是需要窥天测地的几何学。商业发展，计算日繁，便出现了代数学。要描绘动态，研究关系的变化，变化的关系，因
而出现了解析之学、微积分等等。

数学的用处在物理科学上已经经过历史考验而证明。它在生物科学和社会科学上的作用也已经露出苗头。在在着十
分宽广的前途。

最后，我得声明一句，我并不是说其它科学不重要或次重要。应当强调的是，数学之所以重要正是因为其他科学的
重要而重要的，不通过其他学科，数学的力量无法显示，更无重要之可言了。

需要指出的是，“四人帮”为了复辟资本主义，疯狂地破坏生产，破坏科学技术的发展，他们既破坏理论研究工作，
更疯狂地打击从事应用数学的工作者，他们要的是无文化的体力劳动者，供他们剥削。他们的遗毒需要彻底清除，不可
低估。为了在本世纪末实现“四个现代化”，为把我国建成强大的社会主义国家这一伟大目标，发展数学的重要性是无可
置辩的。
