# 谈谈数学打基础问题 {.unnumbered}

学数学，我一向提倡学生多演算一些习题，这有利于弄清基本概念、定义，以至于达到熟练运算的程度。
这就是非常重要的基本功。我青年时代学数学，就养成多解题的习惯。我首先把教科书上的规定的习题，
通过自己独立思考把它解出来，从中领会其所依据的是什么基本概念，什么定理，然后思考是否还能用
别的方法解题，把这道习题真正搞懂。有一次，我曾用大同小异的二十种方法解一道题，互相比较，从
中找出最简便的一种方法。由于基本功扎实了，后来我在演算其他题目是，就感到运用自如。

伹是，目前有人对解题的意义认识有偏差，以为题目做得越多，考试命中率就越高。于是家长、老师忙于收集各类
习题，历届高考试题，竞赛题，外国中学生试题等，统统要求学生做出来，幻想从中碰上升学的试题。这种“题海战术”
式的解题，实际上是一种变相的下赌注。它不利于学生基本功的训练，对提高学习成绩收效甚微。其实，每年高考，数
学试题的类型就那么一些，但题目却变化万千。你做这题，他出那题，完全相同的题几乎没有。如果定理不熟，不会应
用，有时看上去象是“对上号"，结果还是要解错的。所以，“题海战术”只能加重学生的负担，不利于学生的健康成长，
不可能真正提高教学质量。前几年，我收到一位外省青年学生寄来十公斤重的笔记本,打开一看,全是数学习题解答，起
码有七八千道。他附信说，自己解了这么多题，数学高考还是考不好，身体也搞坏了，这件事足以发人深省。

有的青年写信问我学好数学有什么“秘诀”。我想了-下，认为学数学要打好基础，是一个根本问题。初等数学的
基础就是算术、代数、几何、三 角，学好这些学科才有可能学高等数学，高等数学的基础应该说是解析几何和微积分，
由此可见：算术、代数、几何、三 角是数学的基础的基础。中小学生要在解数学习题上能够做到多快好省，必须牢固地
学好这四门学科的基础知识，这应该说是唯一的“秘诀”罢。所谓“学好”，是指把各学科的内容即教科书内容包括其中所
有习题学得深透，演算得烂熟，真正做到没有一个定理不会证，没有一个习题不会做的程度。

我们为什么要演算习题呢？第一，是为了加深对书本中的基本概念、定义和定理的理解，这是主要的。第二，也是
为丁训练我们的运算技巧和逻辑思维。这虽是次要的，但是必不可缺的。习题是不可不做的，多做些习题,对于加深理解
和提高运算技巧，逻辑思维都是有利的。但必须指出，光靠演算习题而忽视学深学透教科书中的基本概念、定义、定理
（包括征明），首先是学不好数学，因而也演不出改头换面的习题来的。

我这里举一个数学竞赛试题为例，来说明学深学透教科书中的基本概念、定义、定理的重要性。题目是这样的：经
过一条定二次曲线上的二定点A和B，任意作圆，使和二次曲线再交于另外二点C和D，求证连线CD常有一定的方
向。这确是什么书上都没见到过的试题,乍看起来是有点难。我们的看法是这样: 大部分考生做不出这道题，不是因为问
题太难太偏、而是因为他们没有学深学透解析几何的基本内容。哪些是解机几何的基本内容呢？

第一，为了讨论几何图形的方便，我们要恰当地选择坐标系(指的是正交坐标系)，使问题中有关图形的表达式化为简单
的形式。在上述的试题里,我们选A为坐标原点O，直线AB为x轴，于是B的坐标便为（1,0），而AB的方程化为y=0。

第二，二次曲线的方程关于x,y是二次的。比方说$f(x, y)=0$，由于要通过A和B，所以方程是:
$$f(x, y)=x^2+2hxy+ by^2-lx+ cy = 0$$
式中h，b，c都是已知的，至于经过A和B的任意元，它也具有同一形式的方程,不过想x^2和y^2的系数相等面且没有$xy$，
这是圆方程的特点，所以圆的方程是：
$$g(x,y)=x^2+y^2-lx+my=0$$
式中的$m$是任意的。

第三，两条二次曲线一般有四个交点。就上列的二次曲线和圆看，A，B，C，D就是这四个交点。 现在我们作方
程：
$$f(x,y) - g(x,y)=0$$
并研究这条新的二次曲线。可是这个方程可以写成；
$$2hx+(b-1)y+c-m=0$$
所以它表示经过四个交点的两条直线。由于 $y=0$ 表示直线AB，所以
$$2hx+(b-1)y+c-m=0$$
应该是直线CD的方程了。从此看出直线CD的斜率$\frac{2h}{1-b}$是常数（和$m$无关）。

我恳切地希望广大中学同学在中学数学教师的指导下,学好各门数学的基础知识，有计划、有步骤地练好做习题的
计算技巧和逻辑思维，适当挑选一些辅助习题而不是盲目贪多地去找习题。我也恳切地希望中学数学教师指导青年人更
好地学习数学基础知识，使他们更快地成长起来。


