# 要讲究学习方法 {.unnumbered}

我常收到一些中学生来信，谈及学习中遇到的种种问题。可以看出，这些同学都有一股强烈的求知欲，也想使自
已的成绩出众，然面或绩总是提不上去。他们不服气，因为论努力的程度，并不亚于成绩比自己好的同学。成绩
不佳的原因是多方面的，但从来信中谈到的情况看，不讲究学习方法，不重视打好基础，恐怕也是学习成绩差的原因之一。

常言道，过河需要有桥，学习不能不注意学习方法。一般说来，学习成绩好的同学，大多数都能联系自己的实际情
况,讲出几种行之有效的学习方法,譬如解题时要注意审题,运算当中要防止粗枝大叶，演算要多采用几种方法，得出结
果之后应该验算等等。同学们可以学习别人的好方法，也可以靠自己在学习中开动脑筋，不断摸索和积累新的方法。但我
总觉得，在研究学习方法时，一定不要忘记打好基础和改进学习方法之间的关系。这篇短文不可能细谈具体的某个学习
方法，我只想针对同学中提出的一两个较普遍的问题，谈谈自己的看法。

“我看到题目，自己想不出解题的方法，当别人 稍加提示，就能做出来。”有的同学来信淘问，这究竟是个什么问
题? 依我看，这主要是基础知识掌握得不扎实，对概念和定理没有真正弄懂。我们为什么要演算习题呢？第一，是为了
加深对书本中的基本概念、定义和定理的理解，这是主要的。第二，也是为了训练我们的运算技巧和逻辑思维。这虽是次
要的，但是必不可少的。做习题，对于加深理解和提高运算技巧、逻辑思维都是有利的。但必须指出，光靠演算习题而
忽视学深学透教科书中的基本概念、定义、定理（包括证明）,肯定是学不好数学的。所以，我们在解题时，首先要看消楚
这道题包含了哪些基础知识，会用到哪几个公式或定理，然后从某个公式或定理下手，一步步将题解出来。有的同学需
要别人提示才能做出来，这就是自己不知从何处下手，需要别人给予具体的指点，说明他对需要运用的定理或公式没有
真正弄懂，在使用中要么无从下手，要么下了手把题目解错了。由此可见，在学习中我们必须反对不懂装懂的不良学风,
懂就懂，绝对不能使用“不太懂”这类含糊其词的话米对待学习。

“我做习题，单个的定理或公式的运用，还可以，遇到综合性的题目，就怎么也想不出解题的办法。”这毛病又出
现在哪呢? 我认为，这些同学对定理或公式虽然懂了，但这大多是靠死记硬背的，对这些定理之间的内在联系缺乏了
解，更没有达到融会贯通的程度，这应当说是不熟的毛病。定理怎么可以靠死记硬背来掌握呢？我们要学好数学，这个
“学好”，我理解是把算术、代数、几何、三角这几门基础学科的内容，即教科书内容包括其中所有习题学得深透，演
算得烂熟，真正做到没有一个定理不会证，没有一个习题不会做的程度。这样，遇到综合题，就能把几个单一的定理公
式融会贯通起来思考，再加上熟能生巧，综合题就不难解出来了。当然，要达到这样的程度，这并不是显而易到的事。
譬如有的平面几何题目，在运算解题中需要画一条辅助线，这条线画在什么地方大有讲究，这确实是有一定的难度。画
准了，一下子就能解出来，画不准，就可能解不出来，即使解出来，也可能是错误的答案。那么，怎样才能有把握一画
即准呢？这就要靠平时的锻炼，按类型来练，演算多了，积累的经验也就丰富了。从另一个方面来说，演算习题还要经
受失败的考验。有的同学一发现解不出，就不肯多动脑筋，总希望别人指点，这样自己就缺乏独立解题的能力，稍为难
点的题目就望而生畏，缩手缩脚，这也是不利于解题能力的。所以，从某种意义上说，经过自己解出的题目，尽管时
间多花了一点，但对定理和公式的理解和运用，印象就深刻得多了。

“我的脑子笨，也许不是学数学的料子。”有的同学在解题中多次碰到困难之后，往往容易产生悲观情绪和无所作为
的思想。有的同学则显得非常急躁，到处求师，希望能得到一套现成的学习方法，使他在几天之内变聪明起来，学习成
绩一下子提上去。这种想法是不现实的。因为学习这东西，是有其规律性的，必须由浅入深，由易到难，由低到高，循
序渐进，别人的学习方法是他自己总结出来的，是针对他自己的情况而定的。别人的好方法，不能生搬硬套。目前学习
成绩较差的同学不要悲观，不要性急，须知，欲速则不达。正确的态度是，既向同学学习好方法，为我所用，更重要的
是，要下决心，从打基础抓起，一点一滴，扎扎实实，把所学的定理、公式及其证明真正搞懂，弄熟，这样也许时间多
花了，效果也许慢了一点，但提高成绩的效果也许会明显一点。


