# 学习数学的几点体会 {.unnumbered}


## 认识学习数学的重要性 {.unnumbered}

从远古到今天，人们都要和数学打交道。1，2，3,…这些简单的整数，从日常生活到尖端科学技术都离不开它们。
由于生产的需要而引起了初等几何学的产生与发展。每一门学问，当它们需要用数量来精确刻划时，都离不开数学。科
学技术越发展,就越需要更多更深的数学作为工具。特别是在电子计算机产生之后，更为数学方法的广泛使用与渗透，开
辟了前所未有的广阔前景。由于计算数量太大，不少过去以为不可能计算的问题，现在都有可能计算了。不仅是力学、
天文学、物理学、工程技术等这些经常需要用数学的领域，即使过去不常用数学的领域，如化学、物理学、经济学与工厂
企业管理等，都日益离不开数学，而且用到很深的数学。值得指出的是，有了好的数学逻辑思维的训练，再去学习与研
究别的很多领域，往往是易于深入的。所以数学几乎是所有人必须掌握的强有力的工具。因此可以说，数学的重要，正
表现在其他学科的重要是它们对于数学的需要上面。

## 掌握基本概念 {.unnumbered}

从远古到今天，人们都要和数学打交道。1，2，3，$\cdots$这些简单的整数，从日常生活到尖端科学技术都离不开它们。
由于生产的需要而引起了初等几何学的产生与发展。每一门学问，当它们需要用数量来精确刻划时，都离不开数学。科
学技术越发展,就越需要更多更深的数学作为工具。特别是在电子计算机产生之后，更为数学方法的广泛使用与渗透，开
辟了前所未有的广阔前景。由于计算数量太大，不少过去以为不可能计算的问题，现在都有可能计算了。不仅是力学、
天文学、物理学、工程技术等这些经常需要用数学的领域，即使过去不常用数学的领域，如化学、物理学、经济学与工厂
企业管理等，都日益离不开数学，而且用到很深的数学。值得指出的是，有了好的数学逻辑思维的训练，再去学习与研
究别的很多领域，往往是易于深入的。所以数学几乎是所有人必须掌握的强有力的工具。因此可以说，数学的重要，正

不断地抽象是数学的特性之一。1，2，3,…是一个人,一个桔子，两张桌子等等的抽象，其四则运算可以概括无穷
多个具体事物间的四则运算。初等几何中的直线与圆等，在现实生活中都是没有的。所谓圆就是与一点等距离的点的轨
迹。现实生活中的圆盘子与脸盆的周围只是近似的圆。但许多具体对象，一经抽象，就能概括得更广泛。由此而得到的
规律，可以在更广泛的实践中得到运用。学习数学时，不断会碰到新的抽象概念。在小学时，会碰到整数、质数、分数、
小数的概念。中学的代数，用文字代替具体的数字，除普通平面几何外，在解析几何中，引进了直角坐标系，所以空间
的点有了坐标表示，从而可以用代数方法处理几何问题。进了大学，微积分的第一关就是新加入了无穷小与无穷大的概念，
极限的概念。如此等等。

学习数学首先就要弄清楚一个个概念。否则脑子里难免是一盆浆糊。掌握抽象概念的办法是多想想具体的例子.例如
二分之一等于四分之二，可以说想象为一块月饼的半块等于两块四等分块月饼。中学的代数方程可以看作一些数满足的
关系式，其中有一个未知数。用数的四则运算法则，可以将这个未知数求出来。这样与算术就可以一致起来。有了未知数
的引进，就可以将算术的四则应用题用方程表示出来，十分易解。而这类问题。如果用算术方法去做，则要困难得多。
解析几何也是同样的，将平面几何中的点，直线等都用数字（或文字）与方程表示出来，因此问题远比平面几何方法解决
来得容易。在学到极限时，更要多掌握些具体数列求极限的例子。

所以要牢牢地掌握基本概念，一是要多了解这一概念的具体例子，二是要对照过去学过的东西，看看有了新概念与方法，到底
有什么优越性？这样还可以把学过的东西有机地联系起来，加深对新概念的理解。

## 勤于思考与动手 {.unnumbered}

仅仅弄清楚概念还不够，还要勤于动手。否则不仅会眼高手低，而且对概念的了解也很浮浅。在学校学习数学的阶
段，适当地多做一些习题是很有必要的，真正弄清楚一个新的概念与方法的标准是看掌握运用它们的水平如何。而这
些是需要通过做习题，即通过独立思考，自己多动手做才能学会。因此一定要勤于思考与动手。当然,同样水平的题目,
特别是代公式的习题、做它许许多多，也是不必要的。要做一些经过思考以后才能够得到答案的较难的习题。更要养成
一个好习惯，就是不要看不起容易的东西，不要放过每一个可以锻炼自己的机会。我国著名数学家华罗庚教授说过,“搞
数学要拳不离手，曲不离口”。他是善于利用一切机会思考数学问题的榜样。例如 1961 年报纸登载苏联向太平洋海域发
射火箭，公报中给出了由四个点构成的一个火箭头着落区城，他就由此去推算出火箭的发射点。又如 1953 年，匈牙利
数学家保尔·吐朗来我国访问时，曾报告了由他给出的我国古代数学家李善兰的一个恒等式的证明，其中用了不少高深
数学知识。华老连夜思考，终于在吐朗离北京前夕，给了李善兰恒等式一个纯初等的证明，并将结果告诉吐朗，为我国
数学家争了气。我跟华老学习与工作，深深体会到这是一个很好的方法。例如，到本世纪末，我国工农业总产值要翻两番。
利用对数知识可以算出年递增率为百分之十七点二左右。这个结论不用对数知识可不可以算出来? 我算过，是可以的。

华老还教导我们,在遇到一个数学问题时,要学会分析，逐步将问题化简，最后加以解决。解决之后，要多想想是不
是走了弯路? 有没有更简单的证明? 要这样反复推敲提高。还要学会心算，学会利用零星时间想问题。他告诉我们在学
习一条定理时，一定要多想想，多分析一下这个定理是怎样创造出来的。这样的分析不仅可以破除对著名数学家的迷
信，对于培养与提高自己以后独立解决问题的能力会有很大的作用。在我跟华老学习与工作的三十多年里，曾多次看到
他解决一些数学问题的全部思索过程。这对培养我学数学与研究数学的能力是受益不尽的。

要勇敢的暴露自己的嵘点。争取别人的帮助。中国民间有旬话：“不要重门弄斧”。说的是你不要到鲁班面前去玩弄
斧头。意思是不要到专家内行面前去谈论他们内行的东西，以免暴露缺点，弄销丢脸。在旧社会，为了生计，这可以说
是一句处事格言。但这决不是鼓励人上进的话。华老把它改为“必需到班门弄斧”。因为只有到班门去弄斧，才能得到最
多的批评与帮助。华老是最善于向别人的优点学习的人。他听别人演讲时，常常打破锅子问到底。有时还对别人的工作
加以简化提高。对学生则更为严格，学生演讲时，常常被问得下不了讲台。他写的东西，在发表前，总是让学生看看，
提的意见愈多，他就愈高兴，师生关系也就越亲密。不少东西，他还专门寄交国内外专家提意见，争取得到帮助。
在他出国讲学时，每到一个学校，专门讲对方特别高明的东西，华老这样做，就是为了从他们那里得到真正的批评与
更多的帮助。华老之所以能够成为有多方面卓越贡献的数学家,除他本人的天分与努力之外，跟他善于学习别人的长处
也是分不开的。还应指出，有些人专喜欢做偏题怪题，所谓偏题怪题都是孤立的东西，只不过是玩弄一些特殊技巧而已，
并无助于加深对数学基本概念与内容的了解。这种学习方法是不可取的。

## 循序前进 {.unnumbered}

学数学最怕的是吃夹生饭。如果一些东西学得糊里糊涂,再继续往前学,则一定越学越糊涂。结果将是一无所获。
所以不要怕学得慢，一定要学得踏实。常常起步慢一些，只要学得很踏实，后来就会快起来的。学习要少而精，力求达
到彻底掌握。华老常说:“要正确估计自己，如果不行，就要退，一直退到懂的地方再继续前进。"华老问我们问题时，
回答一定要求干脆，懂就说懂。不懂就说不懂。说什么“大致差不多”之类不确切的话、他是决不允许的。学数学更不可
以打肿了脸充胖子，假装懂了很多东西。现在有不少人，连初等数学都不掌握，更不用说对近代的数论文献有所了解。
却听不进好言劝告，在那里“研究"费马大定理和哥德巴赫猜想，浪费了很多宝贵的光阴，毫无所获。反而将很多错误的
东西当成正确的东西，印在脑子里，对以后的学习与工作，都将起着很坏的作用。这当然是一种极端的情况。
但确有不少人，当学到一定水平后，就再也学不进去了。究其原因，就是某些部分吃了夹生饭之故。

当然也要防止永远停留在一个水平上，不再继续前进的偏向。有些人掌握了一些工具，例如初等数学，就停留在这
个水平上,用这些工具解决一些问题,不再继续学习与提高。结果是观点很低，水平很低。这是又一种偏向。特别是一帆
风顺，有了一些成绩的人容易犯这个毛病。应该承认学习与掌握一个自己不熟悉的新东西是很费劲的，而且有时还要冒
点风险。这就是要向自己的懒惰与安于现状的心理作斗争。关于这一点，我们特别要向华老学习，他永远不知满足。当
他在四十年代，已经成为国际著名数论学家后，不停步。宁肯另起炉灶，换抽象代数学与复分析。在他老年时，还从事
应用数学的研究与普及。他是既很踏实，又不保守，在数学上，做到了活到老，学到老，工作到老。他的治学经验是值
得我们很好地研究，继承与学习的。

以上是几点不成熟的意见，不妥之处，还望读者不各指教。